# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WsyFM1qPNPV-kByKNY2MUSeahxMmmwMP
"""

from flask import Flask, render_template, request
import joblib
import numpy as np

# Load model dan scaler dari file .pkl
model = joblib.load("Prediksi_diabetes_pada_Pima_Indians.pkl")
scaler = joblib.load("Prediksi_diabetes_pada_Pima_Indians.pkl")

app = Flask(__name__)

@app.route("/")
def home():
    return render_template("index.html")

@app.route("/predict", methods=["POST"])
def predict():
    try:
        # Ambil input dari form
        input_features = [float(x) for x in request.form.values()]
        input_array = np.array([input_features])

        # Scaling input
        input_scaled = scaler.transform(input_array)

        # Prediksi
        prediction = model.predict(input_scaled)[0]
        probability = model.predict_proba(input_scaled)[0][int(prediction)]

        return render_template("index.html", prediction=prediction, prob=round(probability*100, 2))
    except Exception as e:
        return render_template("index.html", prediction="Invalid input", prob=0)

if __name__ == "__main__":
    app.run(debug=True)